---
- name: Packages - DNF - Enable copr repositories
  become: true
  community.general.copr:
    name: "{{ item }}"
  loop: "{{ repos.copr }}"

- name: Packages - DNF - Install packages
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.dnf }}"

- name: Packages - Flatpak - Enable Flathub repo
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Packages - Flatpak - Disable Fedora repo
  become: true
  community.general.flatpak_remote:
    name: fedora
    state: absent

- name: Packages - Flatpak - Install packages
  become: true
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.flatpak }}"
  
- name: Packages - Install VSCodium
  ansible.builtin.import_tasks: installers/vscodium.yml
