---
- name: Packages - DNF - Enable copr repositories
  become: true
  community.general.copr:
    name: "{{ item }}"
  loop: "{{ repos.copr }}"

- name: Packages - DNF - Install packages
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.dnf }}"

- name: Packages - Flatpak - Enable Flathub repo
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Packages - Flatpak - Disable Fedora repo
  become: true
  community.general.flatpak_remote:
    name: fedora
    state: absent

- name: Packages - Flatpak - Install packages
  become: true
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.flatpak }}"

- name: Packages - Install Oh My Zsh
  ansible.builtin.import_tasks: installers/oh_my_zsh.yml

- name: Packages - Install VSCodium
  ansible.builtin.import_tasks: installers/vscodium.yml

- name: Packages - Install OpenCode
  ansible.builtin.shell:
    cmd: "curl -fsSL https://opencode.ai/install | bash"
    creates: "{{ ansible_env.HOME }}/.opencode/bin/opencode"
